language: ruby
script: 'rspec spec/cql'
bundler_args: --without development
rvm:
  - 1.9.3
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk7
  - openjdk6
# services:
#   - cassandra
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7

